camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks
    component: null
    servlet:
      mapping:
        contextPath: test/*
        server:
  port : 8081